### ISSUE TITLE
能补充一些数据sample？

### ISSUE THREAD

**Issue by gumanchang** [ChaoLiangTHU/rec_now#1]
数据可以脱敏，以及入口函数？

**Comment by ChaoLiangTHU** [comment]
> 数据可以脱敏，以及入口函数？

这个项目是基于tf2的，并不需要真实的业务数据。
项目主要是实现了pairwise loss，用法可以看https://github.com/ChaoLiangTHU/rec_now/blob/main/tests/rec_block/test_pairwise_loss_from_batch.py

其他的示例也可以看test文件夹对应目录的测试文件，都构造了简单的数据进行测试。
